---
abstract: 'Returns your ip address using L<http://geoip.hidemyass.com/ip/>'
author:
  - 'David Farrell <sillymoos@cpan.org>'
build_requires:
  Test::More: '0'
  Test::RequiresInternet: '0.03'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-hmaip
requires:
  Exporter: '0'
  HTTP::Tiny: '0'
  base: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/sillymoose/WWW-hmaip
  repository: https://github.com/sillymoose/WWW-hmaip.git
version: '0.02'
